### ISSUE TITLE
CiviCRM 

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/er-onboarding#1]
account creation please

**Comment by mattl** [comment]
Going to push this until after migration which will be soon

**Comment by mmoreshead** [comment]
This is ready to go now, yes?

**Comment by evarogers** [comment]
Looking forward to getting into CiviCRM - let me know when I can expect to have access, @mattl - thanks!

**Comment by mattl** [comment]
Yep, we're in a bit of a sticky place with this right now. We can certainly give you access to the old site, but we're on the verge of moving to the new one. We can't give you access to the new one. @robmyers had a vague plan to share his login with you, which is a little unorthodox but may work for now.

The new website goes live on Wednesday, after that we'll be pushing ahead putting the new Civi live.

**Comment by robmyers** [comment]
@evarogers yes if that's acceptable let me know and I will send you my login details on the new box.

(We don't want to get the new box's database out of sync with the old one, hence this slightly strange way of doing things.)

**Comment by evarogers** [comment]
@robmyers thank you, logging in with your info would be helpful so I can start to get acquainted! 

@mattl I'm not sure what you mean about wiping the new site for the real donate.creativecommons.org but let me know if this is signaling that I should be doing something in the meantime!

**Comment by mattl** [comment]
So we're migrating CiviCRM from version 4.1 to version 4.6, and moving it
to a new faster server.

We made a copy of the site to test the upgrade, and Rob's going to give you
access to it.

When we finally make the new server the live, production, real CiviCRM
server, we have to copy over the data one more time, which will erase any
changes you make on the test server... but that's good, it's a test server
for a reason. Get stuck in and have a look around.

**Comment by evarogers** [comment]
Thanks for the clarification! This all makes sense. Rob did give me access. Thank you both!
