### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/er-onboarding#2]
account creation please!

**Comment by mattl** [comment]
This one is self-service.

**Comment by mmoreshead** [comment]
So maybe I'll assign @rebeccalendl so she can make sure she creates it?

**Comment by mattl** [comment]
@rebeccalendl Once ER is set up with GitHub, please pass this issue back to Mari.

Mari: https://github.com/creativecommons/er-onboarding/settings/collaboration is the place to add them to this project.
