### ISSUE TITLE
CC Wiki & Teamspace

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/er-onboarding#3]
account creation please!

**Comment by mmoreshead** [comment]
@mattl - should this one actually be "create a CCID" (self serve), then we reassign to you and you give access?

**Comment by mattl** [comment]
Yep.

**Comment by mmoreshead** [comment]
Register here first, then reassign: https://login.creativecommons.org/register.php

**Comment by mattl** [comment]
#5 relies on this

**Comment by evarogers** [comment]
Done!

**Comment by mmoreshead** [comment]
Hey @mattl - her CCID won't let her into teamspace.

**Comment by evarogers** [comment]
Hi @mattl - just a quick note of follow-up that I haven't yet been able to get into Teamspace - I keep getting returned to a login page even after logging in with my CCID.
<img width="1275" alt="screen shot 2016-06-13 at 12 11 39 pm" src="https://cloud.githubusercontent.com/assets/19761819/16125985/092775ca-33ab-11e6-82b7-a50c72e2369c.png">

**Comment by mattl** [comment]
Please try now :)

**Comment by evarogers** [comment]
Yay, I am in! Thank you.
