### ISSUE TITLE
cc-affiliates mailing list add

### ISSUE THREAD

**Issue by evarogers** [creativecommons/er-onboarding#8]
@mattl please add eva to cc-affiliates mailing list - thanks!

**Comment by evarogers** [comment]
checking in on this @mattl - many thanks!

**Comment by evarogers** [comment]
hi @mattl — have I been added to the Affiliates mailing list? I don't think I've received any emails. 

While we're at it — can you add me to any CC manual-add mailing lists that are standard for staff to belong to? I don't want to miss out on the things I'm not aware of. Thanks!

**Comment by mmoreshead** [comment]
hey @evarogers - you can add yourself to lots of them, see teamspace: https://teamspace.creativecommons.org/Email_Lists  Happy to answer questions about ones that aren't active or whatever.

**Comment by mattl** [comment]
The Ibiblio ones, they all have this captcha error.

Looking now :)

**Comment by mattl** [comment]
And I can't get into that list... @gwenfranck has access, it seems.

**Comment by gwenfranck** [comment]
Hi @evarogers you should be added to affiliates mailing list!

**Comment by evarogers** [comment]
thanks @gwenfranck !
