### ISSUE TITLE
Freshdesk reset

### ISSUE THREAD

**Issue by evarogers** [creativecommons/er-onboarding#9]
Hi @mmoreshead and @mattl I have flubbed up my freshdesk passwording and while I tried to create a new password, it's not letting me in. Help? Thanks!

**Comment by mmoreshead** [comment]
Alas I have no admin permissions for this kind of thing.  Sorry Eva :(

**Comment by mattl** [comment]
Try now? You weren't a full agent, but I fixed that.

Also, @mmoreshead is now an admin.

**Comment by evarogers** [comment]
I'm in @mattl - thanks!

**Comment by mmoreshead** [comment]
With great power....
